name: Sonar CI
on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
        check-latest: true
        cache: 'maven'
    - name: Compile with Maven
      run: mvn clean package jacoco:report
    - name: Jacoco Aggregate
      run: mvn jacoco:report-aggregate
